# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WordPress-XMLRPC
version:      1.05
version_from: lib/WordPress/XMLRPC.pm
installdirs:  site
requires:
    Smart::Comments:               0
    XMLRPC::Lite:                  0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
