--- #YAML:1.0
name:                WordPress-XMLRPC
version:             1.15
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    SOAP::Lite:                    0
    XMLRPC::Lite:                  0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
